# Generated by Django 5.1.7 on 2025-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0002_alter_nameentry_options_nameentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
