# Generated by Django 5.1.7 on 2025-07-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0003_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['created_at']},
        ),
    ]
